// Generated by the model-stats export (data/types.ts).
// Do not edit here; change the source and rerun the export.

// Types matching the JSON files in data/

// --- Common ---
export type Service = "openai" | "anthropic" | "gemini" | "fireworks";
export type ModelKey = string;
export type ServiceMap<M extends string, T> = Partial<
  Record<Service, Record<M, T>>
>;

// --- Model names (src/models.ts) ---
export type {
  ClientGeminiModelName,
  ClientModelName,
  KnownAnthropicModelName,
  KnownFireworksModelName,
  KnownGeminiModelName,
  KnownModelName,
  KnownOpenAIModelName,
} from "../model_names.ts";

// --- data/fetch_models.json ---
export type FetchModelsFile = ServiceMap<ModelKey, Record<string, unknown>>;

// --- data/model_costs.json ---
export interface CostEntry {
  max_input_tokens: number;
  max_output_tokens: number;
  input_tier0_cents_million_tokens: number;
  input_tier1_cents_million_tokens?: number;
  input_tier1_start_tokens?: number;
  input_priority_tier0_cents_million_tokens?: number;
  input_priority_tier1_cents_million_tokens?: number;
  output_tier0_cents_million_tokens: number;
  output_tier1_cents_million_tokens?: number;
  output_tier1_start_tokens?: number;
  output_priority_tier0_cents_million_tokens?: number;
  output_priority_tier1_cents_million_tokens?: number;
  cache_read_tier0_cents_million_tokens: number;
  cache_read_tier0_start_tokens: number;
  cache_read_tier1_cents_million_tokens?: number;
  cache_read_tier1_start_tokens?: number;
  cache_read_priority_tier0_cents_million_tokens?: number;
  cache_read_priority_tier1_cents_million_tokens?: number;
  // Cache-write rates. cache_write_* is the model's default write SKU:
  // newer OpenAI models' single write price (1.25x input, no TTL split), or
  // Anthropic's default 5-minute ephemeral TTL (~1.25x base input).
  // cache_write_1h_* is Anthropic's extended 1-hour TTL (~2x base input).
  cache_write_tier0_cents_million_tokens?: number;
  cache_write_tier1_cents_million_tokens?: number;
  cache_write_tier1_start_tokens?: number;
  cache_write_priority_tier0_cents_million_tokens?: number;
  cache_write_priority_tier1_cents_million_tokens?: number;
  cache_write_1h_tier0_cents_million_tokens?: number;
  cache_write_1h_tier1_cents_million_tokens?: number;
  cache_write_1h_tier1_start_tokens?: number;
}

export type ModelCostsFile = ServiceMap<ModelKey, CostEntry>;

// --- data/model_caching.json ---
// How a model's prompt cache is controlled:
//   implicit    — the provider caches prefixes automatically, no API opt-in
//   breakpoints — the request marks cacheable spans (Anthropic cache_control,
//                 newer OpenAI models' cache breakpoints)
//   seed        — the cache is pre-created as a named object and referenced by
//                 handle on later requests (Gemini explicit context caching)
// Every model supports `implicit` plus at most one explicit mechanism.
export type CacheMode = "breakpoints" | "implicit" | "seed";

export interface CachingEntry {
  cache_start_tokens_docs: number;
  cache_start_tokens_test?: number;
  cache_start_tokens_test_error?: string;
  cache_start_tokens: number;
  cache_block_size: number;
  cache_modes: CacheMode[];
}

export type ModelCachingFile = ServiceMap<ModelKey, CachingEntry>;

// --- data/model_map.json ---
export interface ModelMapEntry {
  provider: Service;
  costs?: CostEntry;
  caching?: CachingEntry;
}

export type ModelMapFile = ServiceMap<ModelKey, ModelMapEntry>;

// --- data/model_reduce.json ---
export type ModelFamily = string; // normalized base name, may not be an actual model ID

export interface ReducedEntry {
  provider: Service;
  model_family: ModelFamily;
  variants: ModelKey[];
  costs: CostEntry;
  caching: CachingEntry;
}

export type ModelReduceFile = ServiceMap<ModelFamily, ReducedEntry>;
