// Generated by the model-stats export (shared dollar_amount.ts).
// Do not edit here; change the source and rerun the export.

import { NumberValue } from "./number_value.ts";

export class DollarAmount extends NumberValue<DollarAmount> {
  static readonly zero = new DollarAmount(0);

  static value(value: number): DollarAmount {
    return new DollarAmount(value);
  }

  static sum(items: DollarAmount[]): DollarAmount {
    let total = 0;
    for (const item of items) total += item.value;
    return new DollarAmount(total);
  }

  protected create(value: number): DollarAmount {
    return new DollarAmount(value);
  }
}
