// Generated by the model-stats export (index.ts).
// Do not edit here; change the source and rerun the export.

import { get_encoding, type Tiktoken } from "tiktoken";
import modelStats from "./data/model_stats.json" with { type: "json" };
import type { CostEntry } from "./data/types.ts";
import { DollarAmount } from "./dollar_amount.ts";
import { TokenCount } from "./token_count.ts";
import {
  type CacheRateMultipliers,
  type CostUsageCounts,
  type TokenUsageCounts,
} from "./usage_counts.ts";

export type { CostEntry } from "./data/types.ts";

// --- Types ---

export type Service = "openai" | "anthropic" | "gemini" | "fireworks";
export type ModelKey = string; // TODO: brand this?
export type ModelFamily = string; // TODO: brand this?
type ServiceMap<M extends string, T> = Partial<Record<Service, Record<M, T>>>;

export type PricingTier = 0 | 1;
export type CostServiceTier = "standard" | "priority";

// How a model's prompt cache is controlled: `implicit` (automatic prefix
// caching), `breakpoints` (request marks cacheable spans — Anthropic
// cache_control, newer OpenAI models), `seed` (cache pre-created as a named object
// and referenced by handle — Gemini). Every model has `implicit` plus at most
// one explicit mechanism.
export type CacheMode = "breakpoints" | "implicit" | "seed";

export interface CachingEntry {
  cache_start_tokens_docs: number;
  cache_start_tokens_test?: number;
  cache_start_tokens_test_error?: string;
  cache_start_tokens: number;
  cache_block_size: number;
  cache_modes: CacheMode[];
}

export interface CachingEntryTokens {
  cache_start_tokens_docs: TokenCount;
  cache_start_tokens_test?: TokenCount;
  cache_start_tokens_test_error?: string;
  cache_start_tokens: TokenCount;
  cache_block_size: TokenCount;
  cache_modes: CacheMode[];
}

export interface ReducedEntry {
  provider: Service;
  model_family: ModelFamily;
  variants: ModelKey[];
  costs: CostEntry;
  caching: CachingEntry;
}

type ModelReduceFile = ServiceMap<ModelFamily, ReducedEntry>;

// Every public lookup returns a `matched` flag so callers can detect fallback
// and log/alert on unknown models. `matched` is true for direct / variant /
// family-strip hits, false when we guessed a similar known family. The
// entry's `model_family` field tells callers which family they actually got.
export interface Resolution {
  matched: boolean;
}

// --- Model family helpers (self-contained; mirror shared/models.ts) ---

const VARIANT_SUFFIX =
  /(-\d{4}-\d{2}-\d{2}|-\d{2}-\d{4}|-\d{8}|-0{1,2}\d|-chat-latest|-latest|-preview)$/;

function stripToFamily(id: string): string {
  let base = id;
  let prev: string;
  do {
    prev = base;
    base = base.replace(VARIANT_SUFFIX, "");
  } while (base !== prev);
  return base;
}

// Ordered fallback targets per provider — first is the default baseline.
const POPULAR_MODELS: Record<Service, string[]> = {
  openai: [
    "gpt-4o",
    "gpt-4o-mini",
    "o3",
    "o4-mini",
    "gpt-4.1",
    "gpt-4.1-mini",
    "gpt-5",
    "gpt-4",
  ],
  anthropic: [
    "claude-sonnet-4-6",
    "claude-opus-4-6",
    "claude-haiku-4-5-20251001",
    "claude-sonnet-4-5-20250929",
  ],
  gemini: [
    "gemini-2.5-flash",
    "gemini-2.5-pro",
    "gemini-3-flash-preview",
    "gemini-3.1-pro-preview",
  ],
  fireworks: [
    "accounts/fireworks/models/kimi-k3",
    "accounts/fireworks/models/deepseek-v4-pro-0813",
  ],
};

// Size/capability tier keywords that should align between input and candidate.
const TIERS: Record<Service, string[]> = {
  openai: ["nano", "mini", "pro"],
  anthropic: ["opus", "sonnet", "haiku", "fable"],
  gemini: ["nano", "flash", "pro", "ultra"],
  fireworks: ["flash", "pro"],
};

function tokenize(id: string): string[] {
  return id.toLowerCase().split(/[-.]/).filter(Boolean);
}

// Caller must pass a non-empty `available`; fallbackModel guards this.
function baselineFromPopular(provider: Service, available: string[]): string {
  for (const pop of POPULAR_MODELS[provider]) {
    if (available.includes(pop)) return pop;
    const fam = stripToFamily(pop);
    if (available.includes(fam)) return fam;
  }
  return available[0]!;
}

// Prefix-based provider inference for models that aren't in our data.
// Known models are routed via the flat lookup map; this only kicks in
// for unknown ids that still need a fallback target.
function inferServiceFromPrefix(model: string): Service | undefined {
  if (model.startsWith("claude-")) return "anthropic";
  if (model.startsWith("gemini-") || model.startsWith("deep-research-"))
    return "gemini";
  if (model.startsWith("accounts/") || model.startsWith("fireworks/"))
    return "fireworks";
  if (
    model.startsWith("gpt-") ||
    model.startsWith("text-embedding-") ||
    model.startsWith("davinci") ||
    model.startsWith("babbage") ||
    /^o\d/.test(model)
  )
    return "openai";
  return undefined;
}

// Pull version-like numbers from an id, skipping dates, build suffixes,
// and size annotations. stripToFamily handles most date variants; the
// < 100 cap catches MMDD-style suffixes (e.g. gpt-3.5-turbo-instruct-0914);
// the negative lookahead rejects context/parameter-size markers like 16k,
// 70b, etc. Realistic model versions are single- or two-digit
// (gpt-5, claude-3.5, gemini-3.1).
function extractVersions(id: string): number[] {
  const matches = stripToFamily(id).match(/\d+(?:\.\d+)?(?![kKbBmM])/g) ?? [];
  const out: number[] = [];
  for (const m of matches) {
    const n = parseFloat(m);
    if (!Number.isNaN(n) && n < 100) out.push(n);
  }
  return out;
}

function scoreCandidate(
  input: string,
  candidate: string,
  tiers: string[]
): number {
  const low = input.toLowerCase();
  const cand = candidate.toLowerCase();

  // Substring containment is the strongest signal.
  if (low === cand) return 10_000;
  if (low.includes(cand)) return 1_000 + cand.length;
  if (cand.includes(low)) return 900 + low.length;

  let score = 0;

  const inputTiers = tiers.filter((t) => low.includes(t));
  const candTiers = tiers.filter((t) => cand.includes(t));
  score += inputTiers.filter((t) => candTiers.includes(t)).length * 50;
  score -= candTiers.filter((t) => !inputTiers.includes(t)).length * 20;
  if (inputTiers.length === 0 && candTiers.length === 0) score += 10;

  const inTokens = new Set(tokenize(input));
  const candTokens = new Set(tokenize(candidate));
  for (const t of inTokens) if (candTokens.has(t)) score += 10;

  // Numeric proximity: reward candidates whose versions are close to the
  // input's. When input has no numbers, prefer the "newest" same-tier
  // candidate (highest max version).
  const inNums = extractVersions(input);
  const candNums = extractVersions(candidate);
  if (candNums.length > 0) {
    if (inNums.length === 0) {
      score += Math.max(...candNums) * 2;
    } else {
      for (const n of inNums) {
        let closest = Infinity;
        for (const c of candNums) closest = Math.min(closest, Math.abs(n - c));
        if (closest === 0) score += 30;
        else if (closest <= 1) score += 15;
        else if (closest <= 2) score += 5;
        else score -= 5;
      }
    }
  }

  return score;
}

function fallbackModel(
  provider: Service,
  model: string,
  available: string[]
): string | undefined {
  if (!available.length) return undefined;

  const tiers = TIERS[provider];
  const inNums = extractVersions(model);

  // When the input version is significantly newer than anything we have
  // (e.g. "gpt-99-turbo"), legacy keyword overlaps like "turbo" point us at
  // ancient models. The user is asking about a future/unfamiliar version,
  // so pick the newest candidate instead — restricted to the same tier
  // keyword if the input names one we recognize.
  if (inNums.length > 0) {
    const inMax = Math.max(...inNums);
    const candWithVersions = available.map((id) => ({
      id,
      max: Math.max(0, ...extractVersions(id)),
    }));
    const overallMax = Math.max(...candWithVersions.map((c) => c.max));
    if (inMax > overallMax + 2) {
      const low = model.toLowerCase();
      const inputTiers = tiers.filter((t) => low.includes(t));
      let pool = candWithVersions;
      if (inputTiers.length > 0) {
        const sameTier = candWithVersions.filter((c) => {
          const ct = c.id.toLowerCase();
          return inputTiers.every((t) => ct.includes(t));
        });
        if (sameTier.length > 0) pool = sameTier;
      }
      pool.sort((a, b) => b.max - a.max);
      return pool[0]!.id;
    }
  }

  const baseline = baselineFromPopular(provider, available);
  const popRank = (id: string) => {
    const i = POPULAR_MODELS[provider].indexOf(id);
    return i === -1 ? POPULAR_MODELS[provider].length : i;
  };

  let best = baseline;
  let bestScore = scoreCandidate(model, baseline, tiers);
  for (const cand of available) {
    const score = scoreCandidate(model, cand, tiers);
    if (
      score > bestScore ||
      (score === bestScore && popRank(cand) < popRank(best))
    ) {
      best = cand;
      bestScore = score;
    }
  }
  return best;
}

// --- Cached singletons ---

let enc: Tiktoken | undefined;
function getEncoding(): Tiktoken {
  if (!enc) enc = get_encoding("o200k_base");
  return enc;
}

const reduce = modelStats as ModelReduceFile;

// Flat lookup over every known family + variant. Built once at module load
// so the public API can take just a model id (no provider arg needed).
const FLAT_LOOKUP = new Map<string, ReducedEntry>();
for (const provider of [
  "openai",
  "anthropic",
  "gemini",
  "fireworks",
] as const) {
  const providerData = reduce[provider];
  if (!providerData) continue;
  for (const [family, entry] of Object.entries(providerData)) {
    FLAT_LOOKUP.set(family, entry);
    for (const v of entry.variants) FLAT_LOOKUP.set(v, entry);
    // A fireworks model reaches us under three spellings: the full account
    // id the data files key on and the wire carries, plus the bare catalog
    // name and fireworks/ short form the repo's targets and records use.
    if (provider === "fireworks") {
      for (const id of [family, ...entry.variants]) {
        const bare = id.replace(/^accounts\/fireworks\/models\//, "");
        if (bare === id) continue;
        FLAT_LOOKUP.set(bare, entry);
        FLAT_LOOKUP.set(`fireworks/${bare}`, entry);
      }
    }
  }
}

// Identify the provider for any model id. Direct/variant/family-strip hits
// cover every known model; unknown ids fall back to prefix inference.
export function pickService(model: ModelKey): Service | undefined {
  const direct = FLAT_LOOKUP.get(model);
  if (direct) return direct.provider;
  const family = stripToFamily(model);
  if (family !== model) {
    const stripped = FLAT_LOOKUP.get(family);
    if (stripped) return stripped.provider;
  }
  return inferServiceFromPrefix(model);
}

// --- Model resolution ---

interface ResolvedModel extends Resolution {
  entry: ReducedEntry;
}

// Always returns an entry. Known models hit the flat lookup directly;
// unknown ids are routed by prefix (or openai as the global default when no
// provider prefix matches) and then scored against that provider's
// families. Never throws — callers should check `matched` to detect when
// the lookup fell back.
export function resolveModel(model: ModelKey): ResolvedModel {
  // 1. Direct hit on family or listed variant
  const direct = FLAT_LOOKUP.get(model);
  if (direct) return { entry: direct, matched: true };

  // 2. Strip known suffixes and try the family
  const family = stripToFamily(model);
  if (family !== model) {
    const stripped = FLAT_LOOKUP.get(family);
    if (stripped) return { entry: stripped, matched: true };
  }

  // 3. Fallback: infer provider from prefix (or default to openai), then
  // score within it. Defaulting to openai gives us a sensible answer for
  // ids that match no known provider naming (e.g. "foobar-99-ultra").
  const provider = inferServiceFromPrefix(model) ?? "openai";
  const providerData = reduce[provider];
  if (providerData) {
    const fallback = fallbackModel(provider, model, Object.keys(providerData));
    const fbEntry = fallback ? providerData[fallback] : undefined;
    if (fbEntry) return { entry: fbEntry, matched: false };
  }

  // Last resort: return literally any entry. Only reachable if the data file
  // is missing the default provider, which shouldn't happen in practice.
  for (const p of ["openai", "anthropic", "gemini", "fireworks"] as const) {
    const data = reduce[p];
    const first = data ? Object.values(data)[0] : undefined;
    if (first) return { entry: first, matched: false };
  }

  throw new Error("No model data available");
}

// True only when `model` resolves to a known catalog entry (direct, variant,
// or family-strip hit) — not a guessed fallback. Callers use this to validate
// user-supplied model ids without hardcoding their own model lists.
export function isKnownModel(model: ModelKey): boolean {
  return resolveModel(model).matched;
}

// --- Public API ---

export function getTiktokenCount(text: string): number {
  return getEncoding().encode(text).length;
}

// --- Cost calculation ---

interface RateOptions {
  standardTier0: number;
  standardTier1: number | undefined;
  priorityTier0: number | undefined;
  priorityTier1: number | undefined;
  tier1Start: number | undefined;
  promptSize: number;
  serviceTier: CostServiceTier;
  model: string;
}

function pickRate({
  standardTier0,
  standardTier1,
  priorityTier0,
  priorityTier1,
  tier1Start,
  promptSize,
  serviceTier,
  model,
}: RateOptions): number {
  const usesTier1 = tier1Start !== undefined && promptSize > tier1Start;
  if (serviceTier === "priority") {
    if (usesTier1) {
      if (priorityTier1 !== undefined) return priorityTier1;
      throw new Error(
        `Priority pricing for model ${model} is unavailable above ${tier1Start} input tokens`
      );
    }
    if (priorityTier0 !== undefined) return priorityTier0;
    throw new Error(`Priority pricing is unavailable for model ${model}`);
  }
  if (usesTier1 && standardTier1 !== undefined) return standardTier1;
  return standardTier0;
}

export function getPricingTier(
  counts: TokenUsageCounts
): PricingTier | undefined {
  const tier1StartTokens = resolveModel(counts.model).entry.costs
    .input_tier1_start_tokens;
  if (tier1StartTokens === undefined) return undefined;
  return counts.input.gt(TokenCount.value(tier1StartTokens)) ? 1 : 0;
}

function dollarsForTokens(
  tokens: number,
  ratePerMillionCents: number
): DollarAmount {
  // (tokens / 1M) * cents_per_million_tokens = cents; cents / 100 = dollars.
  return DollarAmount.value((tokens * ratePerMillionCents) / 100_000_000);
}

// Compute per-bucket dollar costs for a usage breakdown. Tier-cliff pricing is
// applied per call against the full prompt size, so this MUST run before any
// cross-call aggregation — once dollars are summed the tier choice is fixed.
//
// Input contract (matches `TokenUsageCounts`):
//   `counts.uncached` is base-uncached input plus any cache-write tokens;
//     cache-write buckets are split out via `counts.cache_write` (the
//     default write SKU) / `counts.cache_write_1h` (Anthropic extended TTL).
//   `counts.input` is the full prompt: `uncached + cached`, which equals
//     base + cache-write buckets + cached.
//   `counts.output` is total billable output tokens.
//   `counts.thinking`, when present, is a slice of `counts.output`
//     (`thinking <= output`) — reported as a proportional fraction of the
//     output dollar cost rather than billed at a separate rate.
//   Providers without cache writes / thinking simply omit those keys.
export function getTokenCost(
  counts: TokenUsageCounts,
  serviceTier: CostServiceTier
): CostUsageCounts {
  const resolved = resolveModel(counts.model);
  const rates = resolved.entry.costs;

  const uncachedTokens = counts.uncached.toNumber();
  const cwTokens = counts.cache_write?.toNumber() ?? 0;
  const cw1Tokens = counts.cache_write_1h?.toNumber() ?? 0;
  const baseInputTokens = uncachedTokens - cwTokens - cw1Tokens;
  const cachedTokens = counts.cached.toNumber();
  const outputTokens = counts.output.toNumber();
  // `counts.input` already equals base + cache writes + cached, so it IS the
  // full prompt size used for the long-context cliff check.
  const promptSize = counts.input.toNumber();
  if (serviceTier === "priority" && !resolved.matched) {
    throw new Error(
      `Priority pricing is unavailable for model ${counts.model}`
    );
  }

  const inputRate = pickRate({
    standardTier0: rates.input_tier0_cents_million_tokens,
    standardTier1: rates.input_tier1_cents_million_tokens,
    priorityTier0: rates.input_priority_tier0_cents_million_tokens,
    priorityTier1: rates.input_priority_tier1_cents_million_tokens,
    tier1Start: rates.input_tier1_start_tokens,
    promptSize,
    serviceTier,
    model: counts.model,
  });
  const outputRate = pickRate({
    standardTier0: rates.output_tier0_cents_million_tokens,
    standardTier1: rates.output_tier1_cents_million_tokens,
    priorityTier0: rates.output_priority_tier0_cents_million_tokens,
    priorityTier1: rates.output_priority_tier1_cents_million_tokens,
    tier1Start: rates.output_tier1_start_tokens,
    promptSize,
    serviceTier,
    model: counts.model,
  });
  const cacheReadRate = pickRate({
    standardTier0: rates.cache_read_tier0_cents_million_tokens,
    standardTier1: rates.cache_read_tier1_cents_million_tokens,
    priorityTier0: rates.cache_read_priority_tier0_cents_million_tokens,
    priorityTier1: rates.cache_read_priority_tier1_cents_million_tokens,
    tier1Start: rates.cache_read_tier1_start_tokens,
    promptSize,
    serviceTier,
    model: counts.model,
  });
  const cacheWriteRate =
    rates.cache_write_tier0_cents_million_tokens !== undefined
      ? pickRate({
          standardTier0: rates.cache_write_tier0_cents_million_tokens,
          standardTier1: rates.cache_write_tier1_cents_million_tokens,
          priorityTier0: rates.cache_write_priority_tier0_cents_million_tokens,
          priorityTier1: rates.cache_write_priority_tier1_cents_million_tokens,
          tier1Start: rates.cache_write_tier1_start_tokens,
          promptSize,
          serviceTier,
          model: counts.model,
        })
      : 0;
  const cacheWrite1hRate =
    rates.cache_write_1h_tier0_cents_million_tokens !== undefined
      ? pickRate({
          standardTier0: rates.cache_write_1h_tier0_cents_million_tokens,
          standardTier1: rates.cache_write_1h_tier1_cents_million_tokens,
          priorityTier0: undefined,
          priorityTier1: undefined,
          tier1Start: rates.cache_write_1h_tier1_start_tokens,
          promptSize,
          serviceTier,
          model: counts.model,
        })
      : 0;

  const outputDollars = dollarsForTokens(outputTokens, outputRate);
  const result: CostUsageCounts = {
    base_input: dollarsForTokens(baseInputTokens, inputRate),
    cached: dollarsForTokens(cachedTokens, cacheReadRate),
    output: outputDollars,
  };
  if (counts.cache_write !== undefined) {
    result.cache_write = dollarsForTokens(cwTokens, cacheWriteRate);
  }
  if (counts.cache_write_1h !== undefined) {
    result.cache_write_1h = dollarsForTokens(cw1Tokens, cacheWrite1hRate);
  }
  if (counts.thinking !== undefined) {
    // Thinking is a slice of output; attribute proportionally. Zero output
    // implies zero thinking under the input contract.
    result.thinking =
      outputTokens > 0
        ? outputDollars.times(counts.thinking.toNumber() / outputTokens)
        : DollarAmount.zero;
  }
  return result;
}

/**
 * The model's cache rates as multiples of its input rate (tier-0 rates; the
 * ratio holds across tiers) — reads typically 0.1, writes 1.25 for newer OpenAI models
 * and Anthropic's 5-minute TTL, 2.0 for Anthropic's 1-hour TTL. Recorded next
 * to stored cost breakdowns so rows stay self-describing as pricing tables
 * change. Write fields are absent when the model has no write SKU.
 */
export function cacheRateMultipliers(model: string): CacheRateMultipliers {
  const c = resolveModel(model).entry.costs;
  const input = c.input_tier0_cents_million_tokens;
  const result: CacheRateMultipliers = {};
  if (input > 0) {
    result.cached_rate_multiplier = Number(
      (c.cache_read_tier0_cents_million_tokens / input).toFixed(4)
    );
  }
  if (input > 0 && c.cache_write_tier0_cents_million_tokens !== undefined) {
    result.cache_write_rate_multiplier = Number(
      (c.cache_write_tier0_cents_million_tokens / input).toFixed(4)
    );
  }
  if (input > 0 && c.cache_write_1h_tier0_cents_million_tokens !== undefined) {
    result.cache_write_1h_rate_multiplier = Number(
      (c.cache_write_1h_tier0_cents_million_tokens / input).toFixed(4)
    );
  }
  return result;
}

// --- Caching & model info ---

export interface CachingInfoResult extends Resolution {
  caching: CachingEntry;
}

export interface CachingInfoResultTokens extends Resolution {
  caching: CachingEntryTokens;
}

export function getCachingInfo(model: ModelKey): CachingInfoResult {
  const { entry, matched } = resolveModel(model);
  return { caching: entry.caching, matched };
}

export function getCachingInfoTokens(model: ModelKey): CachingInfoResultTokens {
  const { entry, matched } = resolveModel(model);
  return {
    caching: {
      cache_start_tokens_docs: TokenCount.value(
        entry.caching.cache_start_tokens_docs
      ),
      cache_start_tokens_test: entry.caching.cache_start_tokens_test
        ? TokenCount.value(entry.caching.cache_start_tokens_test)
        : undefined,
      cache_start_tokens_test_error:
        entry.caching.cache_start_tokens_test_error,
      cache_start_tokens: TokenCount.value(entry.caching.cache_start_tokens),
      cache_block_size: TokenCount.value(entry.caching.cache_block_size),
      cache_modes: entry.caching.cache_modes,
    },
    matched,
  };
}
