// Generated by the model-stats export (shared model_names.ts).
// Do not edit here; change the source and rerun the export.

import {
  ANTHROPIC_MODEL_NAMES,
  FIREWORKS_MODEL_NAMES,
  GEMINI_MODEL_NAMES,
  OPENAI_MODEL_NAMES,
  type KnownAnthropicModelName,
  type KnownGeminiModelName,
  type KnownModelName,
  type KnownOpenAIModelName,
} from "./models.ts";

export type {
  KnownAnthropicModelName,
  KnownFireworksModelName,
  KnownGeminiModelName,
  KnownModelName,
  KnownOpenAIModelName,
} from "./models.ts";

// A model name that came from outside our code, such as a client request or
// the CLI: any string is allowed, and `string & {}` keeps the known names
// offered by autocomplete.
export type ClientModelName = KnownModelName | (string & {});
export type ClientGeminiModelName = KnownGeminiModelName | (string & {});

const KNOWN_MODEL_NAMES: ReadonlySet<string> = new Set([
  ...OPENAI_MODEL_NAMES,
  ...ANTHROPIC_MODEL_NAMES,
  ...GEMINI_MODEL_NAMES,
  ...FIREWORKS_MODEL_NAMES,
]);

// Exact membership: a dated variant or family missing from the lists is not a
// known name.
export function isKnownModelName(name: string): name is KnownModelName {
  return KNOWN_MODEL_NAMES.has(name);
}

/** Parse a model name from one of our own inputs, such as a CLI flag, so a
 *  typo fails before anything runs. */
export function parseKnownModelName(name: string): KnownModelName {
  if (isKnownModelName(name)) return name;
  throw new Error(
    `Unknown model "${name}". Use one listed in @context-cup/model-stats/models.js`
  );
}

function isOneOf<T extends string>(
  names: readonly T[],
  name: string
): name is T {
  return (names as readonly string[]).includes(name);
}

export function isKnownOpenAIModelName(
  name: string
): name is KnownOpenAIModelName {
  return isOneOf(OPENAI_MODEL_NAMES, name);
}

export function isKnownAnthropicModelName(
  name: string
): name is KnownAnthropicModelName {
  return isOneOf(ANTHROPIC_MODEL_NAMES, name);
}

export function isKnownGeminiModelName(
  name: string
): name is KnownGeminiModelName {
  return isOneOf(GEMINI_MODEL_NAMES, name);
}
