// Generated by the model-stats export (shared number_value.ts).
// Do not edit here; change the source and rerun the export.

export abstract class NumberValue<T extends NumberValue<T>> {
  protected readonly value: number;

  constructor(value: number) {
    if (Number.isNaN(value)) {
      throw new Error(`${this.constructor.name}: NaN is not allowed`);
    }
    this.value = value;
  }

  protected abstract create(value: number): T;

  private val(other: T | 0): number {
    return typeof other === "number" ? other : other.value;
  }

  // arithmetic — same unit
  plus(other: T): T {
    return this.create(this.value + other.value);
  }
  minus(other: T): T {
    return this.create(this.value - other.value);
  }
  mod(other: T): T {
    return this.create(this.value % other.value);
  }
  times(val: number): T {
    return this.create(this.value * val);
  }
  dividedBy(val: number): T;
  dividedBy(val: T): number;
  dividedBy(val: T | number): unknown {
    return typeof val === "number"
      ? this.create(this.value / val)
      : this.value / val.value;
  }

  // rounding
  floor(): T {
    return this.create(Math.floor(this.value));
  }
  ceil(): T {
    return this.create(Math.ceil(this.value));
  }
  round(): T {
    return this.create(Math.round(this.value));
  }
  abs(): T {
    return this.create(Math.abs(this.value));
  }

  // comparison — accept T or literal 0
  eq(other: T | 0): boolean {
    return this.value === this.val(other);
  }
  neq(other: T | 0): boolean {
    return this.value !== this.val(other);
  }
  lt(other: T | 0): boolean {
    return this.value < this.val(other);
  }
  lte(other: T | 0): boolean {
    return this.value <= this.val(other);
  }
  gt(other: T | 0): boolean {
    return this.value > this.val(other);
  }
  gte(other: T | 0): boolean {
    return this.value >= this.val(other);
  }
  // `this as unknown as T` is safe: subclasses set T to themselves
  // (`class TokenCount extends NumberValue<TokenCount>`), so `this` is a T at
  // runtime. TS can't see that, hence the cast.
  min(other: T | 0): T {
    if (typeof other === "number") {
      return this.value <= 0 ? (this as unknown as T) : this.create(0);
    }
    return this.value <= other.value ? (this as unknown as T) : other;
  }
  max(other: T | 0): T {
    if (typeof other === "number") {
      return this.value >= 0 ? (this as unknown as T) : this.create(0);
    }
    return this.value >= other.value ? (this as unknown as T) : other;
  }

  toNumber(): number {
    return this.value;
  }
  toString(): string {
    return `${this.constructor.name}(${this.value})`;
  }
  toJSON(): number {
    return this.value;
  }

  // Allow string coercion (template literals, String(), .toString()) so log
  // payloads and error messages render the value naturally. Numeric coercion
  // (arithmetic, comparison) still throws — those paths must use the named
  // helpers to avoid silent type confusion.
  [Symbol.toPrimitive](hint: string): string {
    if (hint === "string") return String(this.value);
    throw new TypeError(
      `${this.constructor.name} cannot be coerced to ${hint}. ` +
        "Use .toNumber(), .plus(), .lt(), etc."
    );
  }
}
