// Generated by the model-stats export (usage_counts.ts).
// Do not edit here; change the source and rerun the export.

import type { ClientModelName } from "./data/types.ts";
import { DollarAmount } from "./dollar_amount.ts";
import { TokenCount } from "./token_count.ts";

export const TOKEN_USAGE_KEYS = [
  "input",
  "uncached",
  "cached",
  "cache_write",
  "cache_write_1h",
  "thinking",
  "output",
] as const;

export type TokenUsageKey = (typeof TOKEN_USAGE_KEYS)[number];

// Durable, immutable token-bucket record. The canonical in-memory shape
// everything else passes around. Fields follow the Anthropic-shaped
// convention and OVERLAP — `input` and `uncached` are rollups that mix
// multiple pricing rates. The cost-side shape (`CostUsageCounts`)
// deliberately diverges and exposes one priced bucket per rate; see there
// for the rate-correct view.
//
// The `<M>` generic lets call sites preserve the literal model name
// through the type system (e.g. `TokenUsageCounts<"gpt-4o">` is distinct
// from `TokenUsageCounts<"claude-sonnet">`). It only brands the record's
// `model` field; the TokenCount values inside are model-agnostic.
export type TokenUsageCounts<M extends string = ClientModelName> = {
  readonly model: M;
  // Full prompt: base_input + cache-write buckets + cached.
  readonly input: TokenCount;
  // Everything NOT served from a cache hit: base_input + cache writes.
  readonly uncached: TokenCount;
  // Cache-read tokens (hits on a prior cached prefix).
  readonly cached: TokenCount;
  // Slice of `output` attributed to reasoning tokens.
  readonly thinking?: TokenCount;
  // Total generated tokens (includes thinking).
  readonly output: TokenCount;
  // Tokens written at the model's default write SKU: newer OpenAI models'
  // single SKU, or Anthropic's default 5-minute ephemeral TTL (both 1.25x
  // input).
  readonly cache_write?: TokenCount;
  // Tokens written to Anthropic's extended 1-hour TTL. Anthropic-only.
  readonly cache_write_1h?: TokenCount;
};

// Per-bucket dollar costs. Each field corresponds to exactly one pricing
// rate, so aggregating across calls (`sumCostUsageCounts`) preserves
// rate-correctness and no field is derivable by subtraction. Use
// `totalCost(cost)` for the grand total across all buckets.
export type CostUsageCounts = {
  // base_input tokens × input rate (the model's primary input rate).
  base_input: DollarAmount;
  // cached (cache-read) tokens × cache_read rate.
  cached: DollarAmount;
  // cache_write tokens × the model's default write rate. Omitted for
  // providers without a cache-write SKU.
  cache_write?: DollarAmount;
  // cache_write_1h tokens × cache_write_1h rate (Anthropic). Omitted as above.
  cache_write_1h?: DollarAmount;
  // output tokens × output rate. Reasoning tokens bill at the output rate
  // so they're already folded into this figure.
  output: DollarAmount;
  // Proportional slice of `output` attributed to reasoning/thinking. Same
  // rate as `output`; tracked separately for observability only.
  thinking?: DollarAmount;
};

/**
 * The model's cache rates as multiples of its input rate, recorded next to a
 * cost breakdown so stored rows are self-describing (rates change over time).
 * Dimensionless ratios: cache reads are typically 0.1, writes 1.25 (newer OpenAI models,
 * Anthropic 5-minute TTL) or 2.0 (Anthropic 1-hour TTL). A write field is
 * absent when the model has no such SKU.
 */
export type CacheRateMultipliers = {
  cached_rate_multiplier?: number;
  cache_write_rate_multiplier?: number;
  cache_write_1h_rate_multiplier?: number;
};

const OPTIONAL_KEYS = ["thinking", "cache_write", "cache_write_1h"] as const;

export const EMPTY_COST_USAGE_COUNTS: CostUsageCounts = {
  base_input: DollarAmount.zero,
  cached: DollarAmount.zero,
  output: DollarAmount.zero,
};

export function emptyTokenUsageCounts<M extends string>(
  model: M
): TokenUsageCounts<M> {
  return {
    model,
    input: TokenCount.zero,
    uncached: TokenCount.zero,
    cached: TokenCount.zero,
    output: TokenCount.zero,
  };
}

// Grand total across every priced bucket. `thinking` is excluded because
// it's a slice of `output` (already counted) — including it would double-bill.
export function totalCost(cost: CostUsageCounts): DollarAmount {
  const c = cost;
  return dollarValue(c.base_input)
    .plus(dollarValue(c.cached))
    .plus(dollarValue(c.cache_write))
    .plus(dollarValue(c.cache_write_1h))
    .plus(dollarValue(c.output));
}

// Look up a cost value by token-side bucket name. `TokenUsageCounts` has
// overlapping buckets (`input` is the prompt total; `uncached` includes cache
// writes) while `CostUsageCounts` is single-rate; this helper bridges them
// for display code that iterates token-side keys. `input` here mirrors the
// token-side meaning: prompt-side total, exclusive of output.
export function costForBucket(
  cost: CostUsageCounts,
  bucket: TokenUsageKey
): DollarAmount | undefined {
  const c = cost;
  switch (bucket) {
    case "input":
      return dollarValue(c.base_input)
        .plus(dollarValue(c.cached))
        .plus(dollarValue(c.cache_write))
        .plus(dollarValue(c.cache_write_1h));
    case "uncached":
      return dollarValue(c.base_input)
        .plus(dollarValue(c.cache_write))
        .plus(dollarValue(c.cache_write_1h));
    case "cached":
      return dollarValue(c.cached);
    case "cache_write":
      return c.cache_write === undefined
        ? undefined
        : dollarValue(c.cache_write);
    case "cache_write_1h":
      return c.cache_write_1h === undefined
        ? undefined
        : dollarValue(c.cache_write_1h);
    case "output":
      return dollarValue(c.output);
    case "thinking":
      return c.thinking === undefined ? undefined : dollarValue(c.thinking);
  }
}

function dollarValue(v: DollarAmount | number | undefined): DollarAmount {
  if (v === undefined) return DollarAmount.zero;
  if (typeof v === "number") return DollarAmount.value(v);
  return v;
}

export function sumTokenUsageCountsForDisplay<M extends string>(
  model: M,
  items: TokenUsageCounts[]
): TokenUsageCounts<M> {
  if (items.length === 0) return emptyTokenUsageCounts(model);

  const optional: {
    thinking?: TokenCount;
    cache_write?: TokenCount;
    cache_write_1h?: TokenCount;
  } = {};
  for (const key of OPTIONAL_KEYS) {
    const values = items
      .map((item) => item[key])
      .filter((value) => value !== undefined);
    if (values.length > 0) {
      optional[key] = TokenCount.sum(values);
    }
  }
  return {
    model,
    input: TokenCount.sum(items.map((item) => item.input)),
    uncached: TokenCount.sum(items.map((item) => item.uncached)),
    cached: TokenCount.sum(items.map((item) => item.cached)),
    output: TokenCount.sum(items.map((item) => item.output)),
    ...optional,
  };
}

export function sumCostUsageCounts(items: CostUsageCounts[]): CostUsageCounts {
  if (items.length === 0) return EMPTY_COST_USAGE_COUNTS;

  const result: CostUsageCounts = {
    base_input: DollarAmount.sum(items.map((item) => item.base_input)),
    cached: DollarAmount.sum(items.map((item) => item.cached)),
    output: DollarAmount.sum(items.map((item) => item.output)),
  };
  for (const key of OPTIONAL_KEYS) {
    const values = items
      .map((item) => item[key])
      .filter((value) => value !== undefined);
    if (values.length > 0) {
      result[key] = DollarAmount.sum(values);
    }
  }
  return result;
}
